categorias = {
        "caracteristicas" : "d_capitulos.csv", 
        "embarazo": "s_capitulos.csv", 
        "trabajo": "r_capitulos.csv",
        "demanda_tratamiento": "q_capitulos.csv",
        "personas_seleccionadas": "personas_seleccionadas.csv",
        "personas": "personas.csv",
        "otras_sustancias": "p_capitulos.csv",
        "heroína": "o_capitulos.csv",
        "extasis": "n_capitulos.csv",
        "basuco": "m_capitulos.csv",
        "cocaina": "l_capitulos.csv",
        "marihuana": "k_capitulos.csv",
        "inhalables": "j_capitulos.csv",
        "estimulantes": "i_capitulos.csv",
        "tranquilizantes": "h_capitulos.csv",
        "ilegales": "g_capitulos.csv",
        "alcohol": "f_capitulos.csv",
        "encuestas": "encuestas.csv",
        "tabaco": "e_capitulos.csv",
        "caracteristicas_adicionales": "d2_capitulos.csv",       
}